FROM ubuntu:22.04


USER root
EXPOSE 8888
ENV HOSTNAME=pipeline

RUN apt -y update \
    && apt install -y  \
    sudo git python3-pip ca-certificates libssl-dev libffi-dev python3-dev build-essential\
    && update-ca-certificates

RUN rm -rf /var/lib/apt/lists/*

RUN adduser --disabled-password --gecos '' samitrix \
    && usermod -aG sudo samitrix \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER samitrix
WORKDIR /workspace

RUN git clone https://github.com/sberkan09/TPipeline.git -b main /workspace

ENV PATH="/home/samitrix/.local/bin:${PATH}"

RUN python3 -m pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host=files.pythonhosted.org \
    --upgrade pip \
    -r requirements.txt \
    opencv-contrib-python-headless==4.7.0.72 \
    jupyterlab


CMD ["jupyter", "lab","--ip=0.0.0.0","--NotebookApp.allow_origin='*'","--port=8889", "--no-browser","--NotebookApp.token=''","--NotebookApp.password=''","--ServerApp.terminado_settings={\"shell_command\": [\"/bin/bash\"]}"]

